name: Auto Approve PR
# This workflow automatically approves PRs from the main author.
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'gourab5139014'
    steps:
      - name: Approve PR
        run: gh pr review "$PR_URL" --approve
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
